baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'John Doe'

disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
defaultContentLanguage = "en"
theme = "main-page"

[params]
    title = "John Doe"
    description = "Personal Web Site"
    copyright = "© John Doe"

    favicon = "img/favicon.png"
    fonts = "css/fonts.css"
    scrollsmooth = true


[params.contacts]
    Github   = "johndoe"
    LinkedIn = "johndoe"
    Telegram = "johndoe"
    Medium   = "johndoe"
    # Mail     = "john@doe.co"  


[params.meta]
    keywords = "Personal, Hobby, Readings"
