# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemesSiteBuilder for an example

name = "Main Page"
description = "Clean theme for Single-Page sites or sites with a Main Page."

license = "MIT"
licenselink = "https://github.com/cc-nogueira/hugo-main-page/blob/master/LICENSE"

homepage = "https://github.com/cc-nogueira/hugo-main-page"
demosite = "https://main-page.hash-bang.dev"

tags = [
  "clean",
  "landing",
  "light",
  "minimal",
  "personal",
  "responsive"
]
features = []

[author]
  name = "Ricardo Nogueira"
  homepage = "https://ricardo.nogueira.cc"
